Updated leksah-process and leksah-server to version 0.10.x.
Unfortunately, I cannot test these updates because gtksourceview doesn't
compile:

  ./gtksourceview2.h:10:48: fatal error: gtksourceview/gtksourceundomanager.h: No such file or directory

Not sure what that means.

git-svn-id: https://svn.nixos.org/repos/nix/nixpkgs/trunk@28341 70bd8c7a-acb8-0310-9f0d-9cc1c95dcdbb